title: DreamSaddle
author: DreamSaddle
email: dreamsaddle496@gmail.com
url: https://dreamsaddle.github.io
baseurl: "/"
description: > # description of the site (multiple lines allowed)
  programmer. java

permalink: /:slug.html

favicon: "favicon.ico" 

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
